### ISSUE TITLE
cloud-init from DO work with scaleway

### ISSUE THREAD

**Issue by sr-tream** [elitak/nixos-infect#80]
With little modify (remove `PROVIDER`):
```yaml
#cloud-config
write_files:
- path: /etc/nixos/host.nix
  permissions: '0644'
  content: |
    {pkgs, ...}:
    {
      environment.systemPackages = with pkgs; [ vim ];
    }
runcmd:
  - curl https://raw.githubusercontent.com/elitak/nixos-infect/master/nixos-infect | NIXOS_IMPORT=./host.nix NIX_CHANNEL=nixos-21.05 bash 2>&1 | tee /tmp/infect.log
```
Source: https://nixos.wiki/wiki/Install_NixOS_on_Scaleway_X86_Virtual_Cloud_Server

Tested and work on instances:
- DEV-1S
- DEV-1M

Also, it must work properly with:
- DEV-1L
- DEV-1XL

Tested with images:
- Ubuntu Bionic - **work**
- Ubuntu Focal Fossa - **doesn't work**
- rockylinux 8 - **doesn't work**
